# Website Settings
title: Dharsha R | Portfolio
description: Computer Science & Business Systems Student
remote_theme: pages-themes/merlot@v0.2.0

# Supported theme options you can type above:
# pages-themes/cayman@v0.2.0
# pages-themes/minimal@v0.2.0
# pages-themes/merlot@v0.2.0
# pages-themes/architect@v0.2.0
# pages-themes/tactile@v0.2.0
# pages-themes/slate@v0.2.0
